name: Android CI Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t android-build .

    - name: Run Android build
      run: docker run --rm -v ${{ github.workspace }}:/app android-build

    - name: Extract APK from container
      run: |
        docker create --name temp-container android-build
        docker cp temp-container:/app/app/build/outputs/apk/debug/app-debug.apk ./app-debug.apk
        docker rm temp-container

    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: app-debug-apk
        path: app-debug.apk
