name: CI/CD Android App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Recreate certs/ from GitHub secrets
        run: |
          mkdir -p mqtt-pipeline/mqtt/certs
          echo "${{ secrets.CA_CRT }}" > mqtt-pipeline/mqtt/certs/ca.crt
          echo "${{ secrets.BROKER_CRT }}" > mqtt-pipeline/mqtt/certs/broker.crt
          echo "${{ secrets.CLIENT_CRT }}" > mqtt-pipeline/mqtt/certs/client.crt
          echo "${{ secrets.CLIENT_KEY }}" > mqtt-pipeline/mqtt/certs/client_key.key

      - name: Build and Push Android App
        uses: docker/build-push-action@v5
        with:
          context: ./android_app
          push: true
          tags: denisapopescu1905/android-app:latest

      - name: List files in root
        run: ls -la

      - name: List files in android_app
        run: ls -la ./android_app

      - name: Make gradlew executable
        working-directory: ./android_app
        run: chmod +x ./gradlew

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Run SonarQube analysis
        working-directory: ./android_app
        run: ./gradlew sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io

      - name: Build and Push Mosquitto
        uses: docker/build-push-action@v5
        with:
          context: ./mqtt-pipeline/mqtt
          push: true
          tags: denisapopescu1905/mosquitto:latest
